version: '2'
services:
    randomizepaginateelasticsearch-app:
        image: randomizepaginateelasticsearch
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://randomizepaginateelasticsearch-postgresql:5432/RandomizePaginateElasticsearch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://randomizepaginateelasticsearch-elasticsearch:9200
        ports:
            - 8080:8080
    randomizepaginateelasticsearch-postgresql:
        extends:
            file: postgresql.yml
            service: randomizepaginateelasticsearch-postgresql
    randomizepaginateelasticsearch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: randomizepaginateelasticsearch-elasticsearch
