version: '2'
services:
    cxp_platform-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
        environment:
            - cluster.name=cxp_platform
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        ports:
            - 9200:9200
            - 9300:9300
